version: 2.1

orbs:
  node: circleci/node@5

executors:
  node-executor:
    docker:
      - image: cimg/node:18.18
    resource_class: medium

jobs:
  initialisation:
    executor: node-executor
    steps:
      - checkout
      - run: 
          name: Installation des dépendances
          command: npm install
      - run:
          name: Vérification de Next.js
          command: npm list next || echo "Next.js non détecté dans le projet!"
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - package-lock.json

  validation_code:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Linting et analyse du code
          command: echo "Analyse de la qualité du code en cours..."
      - run:
          name: Vérification des types
          command: echo "Vérification des typages..."

  construction_projet:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Construction du projet
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .next
            - public

  cleaning_packaging:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Nettoyage et packaging
          command: echo "Nettoyage et du packaging..."

  tests_unitaires:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests unitaires
          command: echo "Lancement des tests unitaires..."

  tests_integration:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests d'intégration
          command: echo "Lancement des tests d'intégration..."

  tests_regression:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests de régression
          command: echo "Lancement des tests de régression..."

  tests_performance:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests de performance
          command: echo "Lancement des tests de performance..."

  tests_securite:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests de sécurité
          command: echo "Lancement des tests de sécurité..."

  tests_compatibilite:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests de compatibilité
          command: echo "Lancement des tests de compatibilité..."

  tests_accessibilite:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests d'accessibilité
          command: echo "Lancement des tests d'accessibilité..."

  tests_charge:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Exécution des tests de charge
          command: echo "Lancement des tests de charge..."

  verification_post_deploiement:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Vérification après déploiement
          command: echo "Vérification que l'application fonctionne après déploiement..."

  surveillance_post_deploiement_production:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Surveillance de l'application en production
          command: echo "Surveillance continue de la production..."

  generation_version:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Création d'un tag de version
          command: |
            DATE_VERSION=$(date +%Y%m%d%H%M)
            TAG_VERSION="prod-${DATE_VERSION}"
            echo "Version de production: ${TAG_VERSION}"
            echo "${TAG_VERSION}" > .version
      - persist_to_workspace:
          root: .
          paths:
            - .version

  preparation_deploiement:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Préparation de l'environnement
          command: |
            echo "Configuration des variables d'environnement..."
            BRANCHE=${CIRCLE_BRANCH}
            
            if [[ "$BRANCHE" == "develop" ]]; then
              echo "export VERCEL_ENV=preview" >> $BASH_ENV
            elif [[ "$BRANCHE" == "integration" ]]; then
              echo "export VERCEL_ENV=preview" >> $BASH_ENV
            elif [[ "$BRANCHE" == "main" ]]; then
              echo "export VERCEL_ENV=production" >> $BASH_ENV
            else
              echo "export VERCEL_ENV=preview" >> $BASH_ENV
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .env*

  deploiement_vercel_production:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Installation de Vercel CLI
          command: npm install vercel
      - run:
          name: Déploiement sur Vercel (environnement de production)
          command: |
            echo "Déploiement vers l'environnement de production..."
            npx vercel --token ${VERCEL_TOKEN} --prod --confirm --no-clipboard

  cleanup_branches:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Suppression des branches feature/* et hotfix/*
          command: |
            git fetch --prune
            for branch in $(git branch -r | grep -E "origin/(feature|hotfix)/" | sed 's/origin\///'); do
              echo "Suppression de la branche: $branch"
              git push origin --delete "$branch" || echo "Impossible de supprimer $branch"
            done

workflows:
  version: 2
  pipeline_complete:
    jobs:
      - initialisation
      - validation_code:
          requires:
            - initialisation
      - construction_projet:
          requires:
            - validation_code
      - cleaning_packaging:
          requires:
            - construction_projet
      - tests_unitaires:
          requires:
            - cleaning_packaging
      - tests_integration:
          requires:
            - cleaning_packaging
      - tests_regression:
          requires:
            - cleaning_packaging
      - tests_performance:
          requires:
            - cleaning_packaging
      - tests_securite:
          requires:
            - cleaning_packaging
      - tests_compatibilite:
          requires:
            - cleaning_packaging
      - tests_accessibilite:
          requires:
            - cleaning_packaging
      - tests_charge:
          requires:
            - cleaning_packaging
      - generation_version:
          requires:
            - tests_unitaires
          filters:
            branches:
              only: main
      - preparation_deploiement:
          requires:
            - generation_version
      - deploiement_vercel_production:
          requires:
            - preparation_deploiement
          filters:
            branches:
              only: main
      - verification_post_deploiement:
          requires:
            - deploiement_vercel_production
      - surveillance_post_deploiement_production:
          requires:
            - verification_post_deploiement
      - cleanup_branches:
          requires:
            - deploiement_vercel_production
          filters:
            branches:
              only: main