version: 2.1

orbs:
  node: circleci/node@5 

executors:
  nextjs-executor:
    docker:
      - image: cimg/node:20
    working_directory: ~/repo  

jobs:

  build:
    executor: nextjs-executor
    steps:
      - checkout 
      - run:
          name: Installation des dépendances
          command: npm install
      - run:
          name: Compilation et build du projet Next.js
          command: npm run build
      - run:
          name: Nettoyage et empaquetage
          command: echo "Nettoyage et empaquetage en simulation"
  
  test:
    executor: nextjs-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Exécution des tests unitaires avec Jest
          command: npm run test
      - run:
          name: Exécution des tests end-to-end (E2E) avec Cypress
          command: echo "Tests E2E avec Cypress (simulation)"
      - run:
          name: Tests de régression
          command: echo "Simulation des tests de régression"
      - run:
          name: Tests de performance
          command: echo "Simulation des tests de performance"
      - run:
          name: Tests de sécurité
          command: echo "Simulation des tests de sécurité"
      - run:
          name: Tests de compatibilité
          command: echo "Simulation des tests de compatibilité"
      - run:
          name: Tests d'accessibilité
          command: echo "Simulation des tests d'accessibilité"

  deploy:
    executor: nextjs-executor
    steps:
      - checkout
      - run:
          name: Installation de Vercel CLI
          command: npm install -g vercel
      - run:
          name: Connexion à Vercel
          command: vercel login --token $VERCEL_TOKEN
      - run:
          name: Déploiement Next.js sur Vercel
          command: vercel --prod --token $VERCEL_TOKEN
      - run:
          name: Vérification post-déploiement
          command: echo "Tests post-déploiement en simulation"
      - run:
          name: Surveillance et suivi de la production
          command: echo "Surveillance de l'application en simulation"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - /^feature.*/  
                - /^hotfix.*/  

      - test:
          requires:
            - build  
          filters:
            branches:
              ignore: 
                - /^feature.*/  
                - /^hotfix.*/   

      - deploy:
          requires:
            - test  
          filters:
            branches:
              only: main 