# .circleci/config.yml

version: 2.1

jobs:

  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building the project..."
  
  unit_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running unit tests..."

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

workflows:
  version: 2

  build-test-deploy:

    jobs:

      - build

      - unit_tests:
          requires:
            - build

      - deploy_dev:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - develop

      - deploy_prod:
          requires:
            - unit_tests
          filters:
            branches:
              only:
                - main