version: 2.1

orbs:
  node: circleci/node@5

executors:
  node-executor:
    docker:
      - image: cimg/node:20.9
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  code_analysis:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Linter et analyse statique
          command: npm run lint

  build_project:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Compilation du projet
          command: npm run build

  unit_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Exécution des tests unitaires
          command: npm run test:unit

  integration_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Exécution des tests d'intégration
          command: npm run test:integration

  deploy_vercel:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Installation de Vercel CLI
          command: npm install -g vercel
      - run:
          name: Déploiement sur Vercel
          command: |
            vercel --prod --token $VERCEL_TOKEN

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install_dependencies
      - code_analysis:
          requires:
            - install_dependencies
      - build_project:
          requires:
            - code_analysis
      - unit_tests:
          requires:
            - build_project
      - integration_tests:
          requires:
            - unit_tests
      - deploy_vercel:
          requires:
            - integration_tests
          filters:
            branches:
              only: main
